title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  project_date:
    label: Year
    type: text
    width: 1/2
  project_method:
    label: Method
    type: text
    width: 1/2
  project_desc:
    label: Project Description
    type: text
  project:
    label: Project
    type: structure
    style: table
    fields:
      project_image:
        label: Image
        type: image
