title: Project
pages: false
files:
  sortable: true
fields:
  title:
    label: Title
    type:  text
  year:
    label: Year
    type:  text
  text:
    label: Text
    type:  textarea
  project:
    label: Project
    type: structure
    style: table
    fields:
      project_title:
        label: Title
        type: text
      project_date:
        label: Date
        type: date
      project_location:
        label: Location
        type: text
      project_image:
        label: Image
        type: image
